# Dockerfile for SQL Server with locale configuration
# Author: [Jesús Ariel González Bonilla]
# Date: [21-06-2024]

FROM mcr.microsoft.com/mssql/server:latest

# Set environment variable
ENV LANG es_ES.UTF-8