# Dockerfile for MongoDB with locale configuration
# Author: [Jesús Ariel González Bonilla]
# Date: [21-06-2024]

FROM mongo:latest

# Set environment variable for locale (if necessary)
ENV LANG es_ES.UTF-8

# Optional: Add any additional configuration or scripts here

# Expose MongoDB port
EXPOSE 27017